### ISSUE TITLE
Global steps and Time to train a model

### ISSUE THREAD

**Issue by S7309** [daniel-kukiela/nmt-chatbot#37]
I am training my model with 20 million paired rows in 'train.to' and 'train.from' file and after whole day of training it is showing that 
"global steps 3100 lr 0.001 step-time 30.11s wps 0.34K ppl 5.95gN 24.58 bleu 0.00" and continuing.
can anyone tell me what does that above line means and how much time it will take more. I am new in this field, so sorry if my question is not appropriate.

**Comment by daniel-kukiela** [comment]
You will need about 160k steps to train model for one epoch, and you should train for at least two epochs.
How to calculate that:
`number if training pairs / batch size` and batch size is 128 by default. That will give you number of steps for full epoch.
Next - step takes 30s. That's a lot compared to 2s for me, so you are using CPU for that instead of GPU.
So how long will it take to do one epoch? At least 55 days.

**Comment by S7309** [comment]
Thank you for reply but I have GeForce 930mx and all of the requirements like CUDA, cuDNN, tensorflow-gpu and tensorflow cpu are installed then why it is using cpu and how can I make that to use GPU instead of CPU.

**Comment by daniel-kukiela** [comment]
What do you mean by "I'm unable to create environment"?

**Comment by hinaamukhtar** [comment]
I'm having different issues, I'm new in deep learning. I have tried theano as a backnd but there were issues with version of anaconda. I was using CUDA 9.1, visual studio 2017. Now Im installing CUDA 8 with visual studio 2015. My system specification, core i5 7th generation, geforce 930 MX gpu windows 10.

**Comment by tolotrasamuel** [comment]
@daniel-kukiela  which GPU are you using to get step-time of 2s ?

**Comment by daniel-kukiela** [comment]
GTX 1080 Ti. But it really depends on model settings. My higher step time was about 2.2s.
