### ISSUE TITLE
text to speech

### ISSUE THREAD

**Issue by WillPhelps1** [daniel-kukiela/nmt-chatbot#45]
is there any text to speech and speech to text codes or program to implement with this kind of like how the first episode was?

**Comment by spiderwisp** [comment]
I saw someone forked this project and created a python web app to interact with it. Not sure if that includes TTS.

Myself, I slapped together a webpage using php that `shell_execs()` the `inference.py` script so I could use javascript to render TTS from the browser, because it's really easy like this:

```
utterThis.voice = voices[0];
utterThis.pitch = 0;
utterThis.rate = 1.15;
synth.speak('Hello World');
```

**Comment by daniel-kukiela** [comment]
We are using browser based TTS as well, but in a diffrent way. You can listen to that here: https://discord.gg/TCUbbH (in case something breaks, and it is breking from time to time, lmk if i'm not already resetting things).
You can also use `gTTS` or `pyttsx`.
That project is embeddable, so you can run inference than do whatever you want with a responses.
