### ISSUE TITLE
Bleu score is stuck at 0.00

### ISSUE THREAD

**Issue by awesomedan153** [daniel-kukiela/nmt-chatbot#66]
Even after training for a long time, my bleu score is stuck at 0.00.  I tried to delete the file and restart it, as well as uninstall everything and reinstall it.

**Comment by pranshu19chester** [comment]
Did you find any solution to this?

**Comment by mapingshuo** [comment]
Me too, still debuging.

**Comment by mapingshuo** [comment]
@awesomedan153 have you solved this issue ?

**Comment by awesomedan153** [comment]
@mapingshuo I've been training it for a while (about 110 thousand steps now) and my bleu score went up to 2.96.

**Comment by mapingshuo** [comment]
@awesomedan153 Do you use default dev (tst2012)and test(tst2013) data (100 lines each), or you use your own data? Because BLEU is calculated depends on the dev and test files.

**Comment by awesomedan153** [comment]
@mapingshuo I've been using my own data.

**Comment by mapingshuo** [comment]
@awesomedan153 I change the dev data to my own data (1000 lines), and the dev bleu score is 0.94 now. Thanks for your help.

**Comment by daniel-kukiela** [comment]
We are feeding that model with pairs of sentences, response sentences are way different for similar answer sentences very often. It is not just straight translation between languages. That's why BLEU is not important here and for big training datasets it'll be usually 0. That's pretty ok. Important thing here is if responses are coherent to questions.
